import React ,{useState} from "react";

const details = [
    {
      id: 1,
      flightname: "AkasaAir.",
      flightnum: " Qp 1653",
      img: "https://images.ixigo.com/img/common-resources/airline-new/AI.png",
      starttime: "06:00",
      startingcity: "BLR",
      duration: "3h 05m",
      layovers: "non-stop",
      endtime: "09:05",
      endcity: "GAU",
      price: "9,920",
    },
    {
      id: 2,
      flightname: "Air-India Express.",
      flightnum: " I5 1982",
      img: "https://images.ixigo.com/img/common-resources/airline-new/AI.png",
      starttime: "16:00",
      startingcity: "BLR",
      duration: "4h 05m",
      layovers: "1h layover",
      endtime: "20:05",
      endcity: "GAU",
      price: "8,660",
    },
    {
      id: 3,
      flightname: "IndiGo.",
      flightnum: " 6E 982",
      img: "https://images.ixigo.com/img/common-resources/airline-new/AI.png",
      starttime: "08:40",
      startingcity: "BLR",
      duration: "3h 05m",
      layovers: "non-stop",
      endtime: "11:45",
      endcity: "GAU",
      price: "6,660",
    },
    {
      id: 4,
      flightname: "Vistara.",
      flightnum: " Uk 752",
      img: "https://images.ixigo.com/img/common-resources/airline-new/AI.png",
      starttime: "10:40",
      startingcity: "BLR",
      duration: "2h 05m",
      layovers: "1h layover",
      endtime: "12:45",
      endcity: "GAU",
      price: "10,860",
    },
    {
      id: 5,
      flightname: "SpiceJet.",
      flightnum: "SG 8531",
      img: "https://images.ixigo.com/img/common-resources/airline-new/AI.png",
      starttime: "5:00",
      startingcity: "BLR",
      duration: "8h 10m",
      layovers: "2h layover",
      endtime: "01:10",
      endcity: "GAU",
      price: "7,530",
    },
    {
      id: 6,
      flightname: "Air-India Express.",
      flightnum: " I5 8541",
      img: "https://images.ixigo.com/img/common-resources/airline-new/AI.png",
      starttime: "22:00",
      startingcity: "BLR",
      duration: "3h 05m",
      layovers: "non-stop",
      endtime: "01:05",
      endcity: "GAU",
      price: "9,720",
    },
  ];
  export default details;
  